//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedShowHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSH_User
    {
        public string LoginEmail { get; set; }
        public string LoginPassword { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public int UserType { get; set; }
    }
}
