//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedShowHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSH_House
    {
        public string HouseID { get; set; }
        public string Address { get; set; }
        public Nullable<int> Status { get; set; }
        public double Area { get; set; }
        public int HouseType { get; set; }
        public int DecorationWay { get; set; }
        public string Description { get; set; }
        public string Ichnography { get; set; }
    }
}
